### ISSUE TITLE
POST request for auth - requires parameters not body

### ISSUE THREAD

**Issue by alexometis** [Pardot/api-docs#150]
The docs say that to get an API key you have to submit a request:
```
POST: https://pi.pardot.com/api/login/version/3
message body: email=<email>&password=<password>&user_key=<user_key>
```

However if you embed the email, password and user_key in the body of the POST it always fails. However if you submit as parameters on the URL, then it works and gives you an api_key. It also works if you submit the data as form-data. 

I tested this using Postman as well as Qlik Sense REST connector.

**Comment by ssddanbrown** [comment]
Just double checked this myself quickly via Postman.

The POST body format pardot shown in the docs is `x-www-form-urlencoded`. You can set a raw POST body in the format shown in the docs but you do need to set the following header for Pardot to accept the request: 

```
Content-Type: application/x-www-form-urlencoded
```
When testing without the header the request would fail as you mentioned. Maybe the docs need an update just to confirm the accepted `Content-Type`?

**Comment by alexometis** [comment]
Yes, I can confirm that works too, so an update in the docs to indicate that would be great.

**Comment by joeyrivera** [comment]
I'll add a ticket to make the authentication process more clear. The login endpoint should always be called using the POST verb and the params SHOULD NOT be passed in as part of the query string. You can use form-data or as you all discovered, x-www-form-urlencoded as long as you also pass in the header Content-Type specifying the application/x-www-form-urlencoded value.

**Comment by l14864011** [comment]
> The docs say that to get an API key you have to submit a request:
> 
> ```
> POST: https://pi.pardot.com/api/login/version/3
> message body: email=<email>&password=<password>&user_key=<user_key>
> ```
> 
> However if you embed the email, password and user_key in the body of the POST it always fails. However if you submit as parameters on the URL, then it works and gives you an api_key. It also works if you submit the data as form-data.
> 
> I tested this using Postman as well as Qlik Sense REST connector.

Hi Alexometis,

I am having hard time setting up Pardot data connection in Qlik Sense using REST connector so that I could query the data in Qlik Sense. The only information I found online is from your post. I am really new this topic. Is it possible that you could show me how to set it up Pardot data connection in Qlik Sense? I have API name, password, and user_key available, but I am not sure how to fill it in here. Would really appreciate your help on this.

![image](https://user-images.githubusercontent.com/55963284/68981899-a74f4600-07ca-11ea-868f-96ea209a3499.png)

![image](https://user-images.githubusercontent.com/55963284/68981933-bf26ca00-07ca-11ea-94a6-ecb523671d98.png)

![image](https://user-images.githubusercontent.com/55963284/68981950-cf3ea980-07ca-11ea-9750-76a07c5a66b4.png)
